topics_dimensions = {
    "String Manipulation": 0,
    "Vectorization": 1,
    "Attributes": 2,
    "Queues": 3,
    "Comprehension": 4,
    "HTTP": 5,
    "Primes": 6,
    "Loops": 7,
    "Error Handling": 8,
    "String Slicing": 9,
    "String": 10,
    "HTML Parsing": 11,
    "Python Libraries": 12,
    "Type Conversion": 13,
    "Flask": 14,
    "Strings": 15,
    "Formatting": 16,
    "Sets": 17,
    "Syntax": 18,
    "Arrays": 19,
    "Control Flow": 20,
    "Pandas": 21,
    "Linear Algebra": 22,
    "Numbers": 23,
    "Matrix Operations": 24,
    "Computational Complexity": 25,
    "JSON Handling": 26,
    "Python-specific Techniques": 27,
    "Vectors": 28,
    "Command Line Arguments": 29,
    "Trees": 30,
    "Tuple": 31,
    "Linear Regression": 32,
    "Algorithms": 33,
    "Slicing": 34,
    "Scikit-learn": 35,
    "Connection": 36,
    "Operators": 37,
    "Arithmetic": 38,
    "Lambda Expressions": 39,
    "Sorting": 40,
    "Serialization": 41,
    "Databases": 42,
    "NLTK": 43,
    "Boolean Logic": 44,
    "Zip": 45,
    "Dictionaries": 46,
    "Range": 47,
    "Plotting": 48,
    "SSH": 49,
    "Conditionals": 50,
    "Binary": 51,
    "Assignment": 52,
    "Filtering": 53,
    "Text Processing": 54,
    "Counting": 55,
    "Integer": 56,
    "Functions": 57,
    "Input": 58,
    "__str__": 59,
    "Int": 60,
    "Indexing": 61,
    "Profiling": 62,
    "Base64 Encoding/Decoding": 63,
    "Variables": 64,
    "Randomization": 65,
    "Min Function": 66,
    "Lambda": 67,
    "API Interaction": 68,
    "Time/Dates": 69,
    "Regex": 70,
    "Nodes": 71,
    "OOP": 72,
    "Map": 73,
    "Visualization": 74,
    "__init__": 75,
    "Regular Expressions": 76,
    "Tree Traversal": 77,
    "Stacks": 78,
    "Heaps": 79,
    "Data Handling": 80,
    "Machine Learning": 81,
    "Methods": 82,
    "Iteration": 83,
    "Parsing": 84,
    "HTML": 85,
    "Length": 86,
    "Sentiment Analysis": 87,
    "Recursion": 88,
    "Data Structures": 89,
    "Summation": 90,
    "Swapping": 91,
    "Libraries": 92,
    "SQL": 93,
    "Lists": 94,
    "Concurrency": 95,
    "Tuples": 96,
    "Math": 97,
    "Bit Manipulation": 98,
    "NumPy": 99,
    "Validation": 100,
    "Sockets": 101,
    "Import Statements": 102,
    "Python": 103,
    "GroupBy": 104,
    "Printing": 105,
    "Dynamic Programming": 106,
    "Yield": 107,
    "JSON": 108,
    "Dates/Times": 109,
    "Copy": 110,
    "Update": 111,
    "Web Scraping": 112,
    "Input/Output": 113,
    "Lambda Functions": 114
}

basic_topics = [
    "String Manipulation",
    "Attributes",
    "Comprehension",
    "Loops",
    "Error Handling",
    "String Slicing",
    "String",
    "Functions",
    "Input",
    "__str__",
    "Int",
    "Indexing",
    "Variables",
    "Randomization",
    "Min Function",
    "Arithmetic",
    "Sorting",
    "Assignment",
    "Counting",
    "Integer",
    "Printing",
    "Lists",
    "Range",
    "Conditionals",
    "Binary",
    "Map",
    "Iteration",
    "Length",
    "Summation",
    "Swapping",
    "Libraries",
    "Tuples",
    "Math",
    "Import Statements",
    "Python",
    "JSON",
    "Dates/Times",
    "Copy",
    "Update",
    "Input/Output"
]

advanced_topics = [
    "Vectorization",
    "Queues",
    "HTTP",
    "Primes",
    "HTML Parsing",
    "Python Libraries",
    "Type Conversion",
    "Flask",
    "Formatting",
    "Sets",
    "Syntax",
    "Arrays",
    "Control Flow",
    "Pandas",
    "Linear Algebra",
    "Numbers",
    "Matrix Operations",
    "Computational Complexity",
    "JSON Handling",
    "Python-specific Techniques",
    "Vectors",
    "Command Line Arguments",
    "Trees",
    "Linear Regression",
    "Algorithms",
    "Slicing",
    "Scikit-learn",
    "Connection",
    "Operators",
    "Lambda Expressions",
    "Serialization",
    "Databases",
    "NLTK",
    "Boolean Logic",
    "Zip",
    "Dictionaries",
    "Plotting",
    "SSH",
    "Filtering",
    "Text Processing",
    "Profiling",
    "Base64 Encoding/Decoding",
    "API Interaction",
    "Regex",
    "Nodes",
    "OOP",
    "Visualization",
    "__init__",
    "Regular Expressions",
    "Tree Traversal",
    "Stacks",
    "Heaps",
    "Data Handling",
    "Machine Learning",
    "Methods",
    "Parsing",
    "HTML",
    "Sentiment Analysis",
    "Recursion",
    "Data Structures",
    "SQL",
    "Concurrency",
    "Bit Manipulation",
    "NumPy",
    "Validation",
    "Sockets",
    "GroupBy",
    "Dynamic Programming",
    "Yield",
    "Web Scraping",
    "Lambda Functions"
]