"""attempted_questions table

Revision ID: f3e45b1e7ad0
Revises: 326de3585f46
Create Date: 2025-03-18 22:27:39.824028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # type: ignore


# revision identifiers, used by Alembic.
revision: str = 'f3e45b1e7ad0'
down_revision: Union[str, None] = '326de3585f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempted_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('elo_value', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempted_questions_id'), 'attempted_questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempted_questions_id'), table_name='attempted_questions')
    op.drop_table('attempted_questions')
    # ### end Alembic commands ###
